# Generated by Django 3.0.3 on 2020-02-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.SmallIntegerField(db_column='Sno')),
                ('recdate', models.DateField(blank=True, db_column='RecDate', null=True)),
                ('old_qtr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ananda_nivas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('budha_nivas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('palash', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kadamb', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('parijaat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bakul', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sahana_aithi_house', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nilgiri', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vindhya', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('admin_block', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('krb', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bodh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_in_kl', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('type_of_reading', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'final',
                'managed': False,
            },
        ),
    ]
